export const QUESTIONS: Record<string, string[]> = {
  "Deserted Island": [
    "What 3 items would you bring for entertainment?",
    "What 3 items would you bring for survival?",
    "Would you try to escape or settle in?",
    "Which book would you bring?",
    "Favorite music to have on an island?",
    "One skill you wish you had to survive?",
    "Deserted island luxury item?",
    "Best way to signal for help?",
    "Ideal companion: friend, stranger, or pet?",
    "Favorite food you’d want with you?",
    "How would you pass the time?",
    "Most important survival tool?",
    "What would you build first?",
    "Would you rather swim or build shelter?",
    "Favorite movie to imagine watching?",
    "Best game to play alone?",
    "What would you miss most from home?",
    "One thing you’d invent to make life easier?",
    "Would you explore the island or just settle in to the first safe space you found?",
    "One habit you’d keep or drop?",
    "Favorite plant or fruit you’d hope to find?",
    "Would you keep a journal?",
    "Nighttime: safe fire or sleep?",
    "One animal you hope to avoid?",
    "Favorite survival show you’d watch?",
    "How would you collect water?",
    "Best way to lift spirits?",
    "Would you fish or hunt?",
    "Favorite scent to remind you of home?",
    "How would you decorate your spot?"
  ],
  "My Favorite Things": [
    "What’s your comfort movie?",
    "Favorite song of all time?",
    "Favorite snack?",
    "Favorite holiday?",
    "Favorite childhood toy?",
    "Favorite outfit?",
    "Favorite way to spend a Sunday?",
    "Favorite restaurant?",
    "Favorite book or author?",
    "Favorite game to play?",
    "Favorite smell?",
    "Favorite coffee or tea drink?",
    "Favorite dessert?",
    "Favorite season?",
    "Favorite color combo?",
    "Favorite way to relax?",
    "Favorite actor or actress?",
    "Favorite genre of music?",
    "Favorite sport to watch?",
    "Favorite sport to play?",
    "Favorite kind of movie night snack?",
    "Favorite childhood memory?",
    "Favorite app on your phone?",
    "Favorite way to exercise?",
    "Favorite inspirational quote?",
    "Favorite TV show?",
    "Favorite animal?",
    "Favorite way to celebrate birthdays?",
    "Favorite type of art?",
    "Favorite thing to learn about?"
  ],
  "Travel & Places": [
    "Dream country to visit?",
    "Beach or mountains?",
    "City or countryside?",
    "Favorite trip you’ve taken?",
    "Place you want to return to?",
    "One food you’d try abroad?",
    "Favorite type of travel: road, train, flight?",
    "Favorite travel companion?",
    "One city you’d live in for a year?",
    "Favorite travel souvenir?",
    "One landmark you want to see?",
    "Favorite type of accommodation?",
    "Adventure trip or relaxing trip?",
    "Best mode of transport?",
    "Would you go solo or with friends?",
    "Best hidden gem you discovered?",
    "Favorite festival abroad?",
    "Travel photo that means a lot?",
    "One travel tip you swear by?",
    "Favorite travel app?",
    "Place with the most beautiful scenery?",
    "One place you’d recommend to everyone?",
    "Best way to meet locals?",
    "Favorite kind of travel weather?",
    "One activity you always do when traveling?",
    "Favorite souvenir to collect?",
    "Best street food you’ve had?",
    "One cultural experience that stood out?",
    "Favorite road trip memory?",
    "One place on your bucket list?"
  ],
  "Would You Rather": [
    "Live without music or TV?",
    "Teleport or fly?",
    "Always be 10 minutes late or have to travel 20 minutes extra to be on time?",
    "Be invisible or be able to read minds?",
    "Only eat sweet or savory foods?",
    "Be able to speak all languages or play all instruments?",
    "Time travel to past or future?",
    "Never use social media or never watch movies?",
    "Always hot or always cold?",
    "Be rich (known / unknown) or famous (rich / broke)?",
    "Talk only in rhymes or in only song lyrics?",
    "Have a personal chef or a personal driver?",
    "Only walk or only bikw everywhere?",
    "Never sleep or never eat?",
    "Live underwater or in the sky?",
    "Be a superhero or a witch/wizard?",
    "Live in winter or summer forever?",
    "Speak only the truth or always lie?",
    "Have a rewind button or pause button for life?",
    "Be able to control animals or plants?",
    "Live in a mansion or on a private island?",
    "Be able to teleport anywhere or be invisible anytime?",
    "Have a robot assistant or a magical pet?",
    "Only watch comedy or only watch horror?",
    "Be best friends with a celebrity or an unknown genius?",
    "Benjamin Button or Dorian Gray?",
    "Have unlimited money or unlimited time?",
    "Only eat at restaurants or only cook at home?",
    "Be a master at one skill or okay at many skills?",
    "Live without internet or without a phone?"
  ],
  "Childhood & Nostalgia": [
    "Favorite childhood toy?",
    "First best friend?",
    "What would your childhood self be most impressed with about you right now?",
    "Favorite game as a kid?",
    "Childhood TV show you still remember (can be a cartoon)?",
    "Favorite childhood snack?",
    "Best birthday memory?",
    "Childhood hero or role model?",
    "Favorite school subject?",
    "Favorite playground activity?",
    "Most mischievous thing you did as a kid?",
    "Favorite bedtime story?",
    "First pet memory?",
    "Childhood hobby you miss?",
    "Favorite family tradition?",
    "Most memorable holiday as a kid?",
    "First bike memory?",
    "Childhood favorite song?",
    "First sleepover experience?",
    "Favorite doll/action figure?",
    "Favorite costume or Halloween memory?",
    "Childhood dream job?",
    "Favorite playground game?",
    "Best friend from school you still remember?",
    "Favorite summer activity as a kid?",
    "First crush memory?",
    "Most embarrassing moment as a child?",
    "Favorite childhood book?",
    "Childhood superstition or silly fear?",
    "What’s one thing you’d tell your childhood self?"
  ],
  "Productivity": [
    "Morning or night worker?",
    "Biggest distraction?",
    "Favorite productivity hack?",
    "Coffee or tea to stay focused?",
    "Best time of day to get things done?",
    "Favorite to-do list method?",
    "Most satisfying task completion?",
    "How do you avoid procrastination?",
    "Best focus playlist or sound?",
    "Favorite productivity app?",
    "Work solo or in a team?",
    "Favorite workspace setup?",
    "Breaks: short and frequent or long and few?",
    "Best way to prioritize tasks?",
    "How do you stay motivated?",
    "Most productive day you remember?",
    "Quickest way to tackle a boring task?",
    "Most unusual productivity tip that works?",
    "How do you track progress?",
    "Favorite motivational quote?",
    "Digital or paper planner?",
    "Do you plan the night before or morning of?",
    "Most distracting app you’ve banned?",
    "Favorite kind of workspace lighting?",
    "Productivity rituals you swear by?",
    "Do you batch tasks or tackle as they come?",
    "How do you manage emails?",
    "One habit that changed your productivity?",
    "Music or silence to focus?",
    "Favorite way to celebrate completing a project?"
  ],
  "Creative Mode": [
    "If you wrote a book, what genre?",
    "Invent a holiday.",
    "Design your dream home.",
    "If you could paint anything, what would it be?",
    "Compose a song title—what’s it called?",
    "Create a new flavor of ice cream.",
    "Reimagine a classic fairytale.",
    "Write a tagline for your life.",
    "Design a new gadget.",
    "Sketch a logo for your imaginary company.",
    "Make up a funny word and its meaning.",
    "What’s the theme of your personal museum?",
    "Recast your favorite movie in a different era.",
    "Create a new superhero or villain.",
    "Invent a new board game.",
    "Redesign a famous landmark.",
    "If animals could talk, write a dialogue.",
    "Make up a joke or pun.",
    "Create a brand new sport.",
    "Design a costume for a futuristic festival.",
    "Write a 2-line poem about today.",
    "Invent a fun household gadget.",
    "Make up a festival for something silly.",
    "Create a new emoji and its use.",
    "Write a motivational poster slogan.",
    "Imagine a new app that doesn’t exist.",
    "Design your perfect workspace.",
    "Write a catchy jingle.",
    "Create a fictional character and describe them.",
    "Build a fantasy map of your dream world."
  ],
  "Superpowers": [
    "Pick a catchy name for the superpower of your choice.",
    "One power with limits?",
    "Hero or villain?",
    "Fly or teleport?",
    "Super strength or super speed?",
    "Read minds or control thoughts?",
    "Time travel or freeze time?",
    "Shape-shift or become invisible?",
    "Speak to animals or control them?",
    "Heal yourself or heal others?",
    "Control fire or water?",
    "Super intelligence or super memory?",
    "One power you’d keep secret?",
    "Turn objects into anything or turn invisible?",
    "Speak every language instantly or understand all animals?",
    "Control the weather or control time?",
    "Walk through walls or walk on water?",
    "Fly solo or with a team of superheroes?",
    "Night vision or X-ray vision?",
    "Best way to use powers for fun?",
    "Use powers for fame or be anonymous?",
    "Best costume for your powers?",
    "Power that’s mostly practical?",
    "Power that’s mostly fun?",
    "If you were part of a superhero team, what would you like your team name to be?",
    "Ability to breathe underwater or fly?",
    "Control technology or control nature?",
    "Power you’d use once a day or all the time?",
    "Sidekick or solo adventures?",
    "Most creative way to use your power?"
  ],
  "Food & Drink": [
    "Food you will never be in the mood for?",
    "Weirdest food you've ever eaten: what was it and where did you eat it?",
    "Pick a city you'd like to visit and name one food / beverage you'd like to try there",
    "Favorite dessert?",
    "Pizza toppings?",
    "Favorite breakfast food?",
    "Best comfort food?",
    "Favorite fruit?",
    "Favorite meat / meat substitute?",
    "Favorite vegetable?",
    "Favorite beverage?",
    "Sweetest treat you’ve ever had?",
    "Spicy or mild?",
    "Homemade or restaurant?",
    "Best ice cream flavor?",
    "Favorite chocolate?",
    "Favorite sandwich?",
    "Favorite fast food?",
    "Go-to homemade recipe?",
    "Drink with meals or no drink?",
    "Favorite soup?",
    "Must-have at any meal (breakfast / lunch / dinner) ~ and no, you can't mention any cutlery",
    "Odd food combo you love?",
    "Favorite cheese (or if you don't can't eat cheese, favorite condiment?",
    "Best summer beverage?",
    "Favorite holiday treat?",
    "Favorite comfort beverage?",
    "Favorite snack to share?",
    "Food you’d take on a trip?"
  ],
  "Rapid Fire": [
    "If you could choose to have either a. A cat or a dog or b. any other type of pet, what would you choose?",
    "Beach or mountains?",
    "Early bird or night owl?",
    "Coffee or tea?",
    "Pizza or burger?",
    "Winter or summer?",
    "Morning shower or night shower?",
    "Book or movie?",
    "Sweet or salty?",
    "Chocolate or vanilla?",
    "Pen or pencil?",
    "Netflix or YouTube?",
    "Mountains or lakes?",
    "City or countryside?",
    "Sneakers or boots?",
    "Phone or computer?",
    "Phone call or text?",
    "Rain or snow?",
    "Music or silence?",
    "Comedy or drama?",
    "Stay in or go out?",
    "Online shopping or in-store?",
    "Cake or pie?",
    "Cat video or dog video?",
    "Morning walk or evening walk?",
    "Sneakers or sandals?",
    "Sweet tea or unsweet tea?",
    "Ice cream cone or cup?",
    "Road trip or flight?",
    "Chocolate bar or candy?"
  ],
  "Software & Programming": [
    "What was the first program you ever wrote?",
    "Tabs or spaces?",
    "What's your favorite programming language and why?",
    "Light mode or dark mode?",
    "What's the most satisfying bug you've ever fixed?",
    "If you could instantly master one technology, what would it be?",
    "What's your go-to text editor or IDE?",
    "What's the worst variable name you've ever seen (or written)?",
    "Do you comment your code or let it speak for itself?",
    "What's a tech buzzword you're tired of hearing?",
    "Would you rather fix someone else's code or rewrite it from scratch?",
    "What's the longest you've spent debugging something silly?",
    "What's your favorite keyboard shortcut?",
    "Do you prefer building frontend or backend?",
    "What's a project you're secretly proud of?",
    "Mechanical keyboard or regular keyboard?",
    "What's the best piece of coding advice you've ever gotten?",
    "Have you ever pushed to production on a Friday?",
    "What's your favorite way to procrastinate while 'thinking about the problem'?",
    "Vim, Emacs, or run away?",
    "What's a tool you can't imagine working without?",
    "What's the funniest commit message you've ever written?",
    "Do you read the documentation or dive straight in?",
    "What's your relationship with semicolons?",
    "If your code were a personality, what would it be like?",
    "What's the most overengineered thing you've ever built?",
    "Rubber duck debugging: genius or nonsense?",
    "What's a programming concept that finally 'clicked' for you?",
    "What would your ideal coding setup look like?",
    "If you could delete one thing from the internet's codebase, what would it be?"
  ],
  "Music & Soundtracks": [
    "What's your personal theme song?",
    "Which song instantly improves your mood?",
    "What's the first album or song you remember loving?",
    "If your life were a movie, what would play over the closing credits?",
    "What's a song you know every single word to?",
    "Which artist have you seen live, or most want to?",
    "What's your go-to karaoke song?",
    "What song always makes you turn up the volume?",
    "What's a guilty-pleasure song you secretly love?",
    "Which movie soundtrack is better than the movie itself?",
    "What song instantly takes you back to a specific memory?",
    "What's the best concert or live show you've ever been to?",
    "Vinyl, streaming, or something else?",
    "What's a song you can't stand but everyone else loves?",
    "Which instrument do you wish you could play?",
    "What's your most-played song this year?",
    "What genre did you love as a teenager?",
    "What song would you pick to pump yourself up before something big?",
    "What's a lyric that's stuck with you?",
    "Who's an artist you could listen to all day?",
    "What's the perfect song for a road trip?",
    "Do you make playlists, or hit shuffle and hope?",
    "What's a song that always makes you want to dance?",
    "Which TV show theme song is unskippable?",
    "What's the most underrated song you know?",
    "If you could duet with any musician, who would it be?",
    "What song would you want played at a celebration?",
    "What's your favorite song to listen to in the rain?",
    "What music do you put on to focus?",
    "If you started a band, what would you name it?"
  ],
  "Hot Takes (Friendly Edition)": [
    "What's a hill you're willing to die on?",
    "What's something people overcomplicate?",
    "What's a food combination you'll defend forever?",
    "What's an overrated thing everyone seems to love?",
    "What's something underrated that deserves more hype?",
    "What's a 'rule' you think is totally pointless?",
    "What's the correct way to load a dishwasher (you're right, obviously)?",
    "Is cereal a soup? Defend your answer.",
    "What's a trend you hope never comes back?",
    "What's something you changed your mind about completely?",
    "What's a small thing that's weirdly satisfying?",
    "What's an unpopular opinion about a movie or show?",
    "Hot dog: sandwich or not?",
    "What's a chore that's secretly not that bad?",
    "What's something everyone pretends to enjoy?",
    "What's the best way to spend a lazy Sunday?",
    "What's a 'fancy' thing that isn't worth the hype?",
    "What's a snack that's perfect exactly as it is?",
    "What's an everyday item that's badly designed?",
    "What's the ideal number of pillows on a bed?",
    "What's something you'd ban if you could, just for a day?",
    "What's a tradition you think we should bring back?",
    "What's the best topping debate you have strong feelings about?",
    "What's a piece of advice you think is overrated?",
    "What's the right age to stop counting your birthdays?",
    "What's something people worry about way too much?",
    "What's the most overrated holiday?",
    "What's a convenience you refuse to give up?",
    "What's something simple that brings you disproportionate joy?",
    "What's your most defensible 'wrong' opinion?"
  ],
  "Entertainment & Pop Culture": [
    "What's a movie everyone loves that you just don't get?",
    "Which fictional world would you vacation in?",
    "What show have you rewatched the most times?",
    "Which fictional character would you want as a roommate?",
    "What's the best movie you've seen recently?",
    "If you could be in any TV show, which one?",
    "What's a book that should be turned into a movie?",
    "Which villain is secretly the best character?",
    "What's your comfort movie when you're feeling down?",
    "Which celebrity would you want to swap lives with for a day?",
    "What's a sequel that was better than the original?",
    "What fictional gadget do you wish were real?",
    "What's the most quotable movie of all time?",
    "Which fictional meal do you most want to try?",
    "What's a show you gave up on, and why?",
    "Who's your favorite fictional duo?",
    "What's a plot twist that genuinely shocked you?",
    "If your life had a narrator, who would you pick?",
    "What's an awards-show moment you'll never forget?",
    "Which cartoon did you love growing up?",
    "What's a movie you can quote start to finish?",
    "Which fictional pet would you adopt?",
    "What's the best opening scene in any movie?",
    "What franchise would you happily never see again?",
    "Which character's wardrobe would you steal?",
    "What's a documentary that changed how you see something?",
    "If you could spoil one ending for fun, which would it be?",
    "What's an underrated show more people should watch?",
    "Which fictional job looks the most fun?",
    "What's the soundtrack you'd want for your own movie trailer?"
  ]
};