import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "./globals.css";

const playpen = Playpen_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-playpen"
});

export const metadata: Metadata = {
  title: "Spin the Icebreaker Wheel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playpen.variable}`}>
        {children}
      </body>
    </html>
  );
}
