import ThemeToggle from "../components/ThemeToggle";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Spin the Icebreaker Wheel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <ThemeToggle>{children}</ThemeToggle>
      </body>
    </html>
  );
}